[package]
name = "day-02"
version = "0.1.0"
authors = ["Nicol√°s Venturo <nicolas.venturo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
